CREATE DATABASE levameulivro_db;
CREATE USER 'JORGE'@'%' IDENTIFIED BY 'JORGE';
CREATE USER 'JORGE'@'localhost' IDENTIFIED BY 'JORGE';
GRANT ALL PRIVILEGES ON *.* to JORGE@localhost;
GRANT ALL PRIVILEGES ON *.* to JORGE@'%';
FLUSH PRIVILEGES